# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-GPSD3
version:      0.11
version_from: lib/Net/GPSD3.pm
installdirs:  site
requires:
    base:                          0
    DateTime:                      0
    GPS::Point:                    0.1
    IO::Socket::INET6:             0
    JSON::XS:                      0
    strict:                        0
    Test::Simple:                  0.44
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
