--- #YAML:1.0
name:               Net-GPSD3
version:            0.18
abstract:           Interface to the gpsd server daemon protocol versions 3 (JSON).
author:
    - Michael R. Davis (domain=>michaelrdavis,tld=>com,account=>perl)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:             0
    DateTime::Format::W3CDTF:  0.06
    GPS::Point:           0.1
    IO::Socket::INET6:    0
    JSON::XS:             0
    Test::Simple:         0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
